---
- name: CIS Benchmark Test
  hosts: "localhost"
  connection: local
  become: yes
  gather_facts: yes

  vars:
    rvm_gpg_key:       409B6B1796C275462A1703113804BB82D39DC0E3
    rvm_gpg_server:    'hkp://keys.gnupg.net'
    rvm_install_path:  '/usr/local/rvm'
    rvm_ruby:          'ruby-2.3.1'
    rvm_ruby_bin_path: "{{ rvm_install_path }}/rubies/{{ rvm_ruby }}/bin"
    cis_compliance_score_threshold: 80
    cis_benchmark_test_dir:         /tmp/cis-ubuntu-14.04-benchmark
    cis_benchmark_test_report:      /tmp/cis-benchmark.report


  pre_tasks:
    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Install git client
      apt:
        name: git
        state: present

    - name: Download rvm installer
      get_url:
        url: https://get.rvm.io
        dest: /tmp/rvm-installer.sh
        mode: 0755

    - name: Import rvm gpg key
      command: gpg --keyserver {{ rvm_gpg_server }} --recv-keys {{ rvm_gpg_key }}
      register: gpg_result
      until: gpg_result.rc == 0
      retries: 5
      delay: 5

    - name: Install rvm
      command: /tmp/rvm-installer.sh stable --path {{ rvm_install_path }}
      register: rvm_install

    - debug: var=rvm_install

    - name: Reload rvm
      command: "{{ rvm_install_path }}/bin/rvm reload"
      register: ruby_install

    - name: Install ruby
      command: "{{ rvm_install_path }}/bin/rvm install {{ rvm_ruby }}"
      register: ruby_install

    - name: Set default ruby
      command: "{{ rvm_install_path }}/bin/rvm alias create default {{ rvm_ruby }}"

    - debug: var=ruby_install

    - name: Install inspec gem
      command: gem install inspec
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ rvm_ruby_bin_path }}"


  tasks:
    - name: Clone CIS Ubuntu 14.04 Linux Benchmark Inspec test suite repo
      git:
        repo: https://github.com/wunzeco/cis-ubuntu-14.04-benchmark.git
        dest: "{{ cis_benchmark_test_dir }}"

    - name: Run CIS Benchmark tests
      shell: >
          inspec exec {{ cis_benchmark_test_dir }} --format=progress > {{ cis_benchmark_test_report }} || true
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ rvm_ruby_bin_path }}"

    - name: Get CIS Benchmark test summary
      shell: >
          grep -E 'examples.*failures.*pending' {{ cis_benchmark_test_report }} \
              | awk '{ s = 100 * ($1 - $3) / $1; print "Summary: " $0 "\n%Compliance: " s }'
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ rvm_ruby_bin_path }}"
      register: summary

    - debug: var=summary.stdout_lines

    - set_fact: cis_compliance_score="{{ summary.stdout_lines|last|regex_replace('.* (.*)$', '\\1') }}"

    - name: Fail if CIS Benchmark compliance score is less than recommended {{ cis_compliance_score_threshold }}% threshold
      fail: msg="%Compliance score of CIS Benchmark ({{ cis_compliance_score }}) is less than {{ cis_compliance_score_threshold }}% threshold"
      when: cis_compliance_score|float < cis_compliance_score_threshold
      register: verify

    - debug: msg="SUCCESS - %Compliance score of CIS Benchmark is {{ cis_compliance_score }}%"


  post_tasks:
    - name: Uninstall git client
      apt:
        name: git
        state: absent

    - name: Uninstall rvm
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ rvm_install_path }}"
        - /etc/profile.d/rvm.sh
        - /etc/rvmrc
        - /tmp/rvm-installer.sh

    - name: Remove rvm group
      group:
        name: rvm
        state: absent

    - name: Clean up cis benchmark test dir
      file:
        path: "{{ cis_benchmark_test_dir }}"
        state: absent
